# Generated by Django 3.2.9 on 2021-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0010_alter_ingredients_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
