# Generated by Django 3.2.9 on 2021-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0011_auto_20211128_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
