# Generated by Django 3.1.3 on 2021-12-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eval1', '0012_alter_history_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
